### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by leonardoaraujosantos** [SullyChen/Autopilot-TensorFlow#20]
Hi @SullyChen did you test training your model without the, scaling operation (atan)?
https://github.com/SullyChen/Autopilot-TensorFlow/blob/master/model.py#L88

Also did you do some sort of preprocessing to do image augmentation and to balance the dataset?
I'm asking this because most of the time the data has no steering.

I've created another driving example based on your code (Including a game and a tcp/ip comm class)
https://github.com/leonardoaraujosantos/DLMatFramework/tree/master/virtual/tensorDriver

Here is a video of my current performance
https://www.youtube.com/watch?v=PT8oToyV85w

**Comment by SullyChen** [comment]
I haven't tested it very much without the scaling operation, although it
likely wouldn't make a massive difference in the result. The main
bottlenecks at this point are training data. I did no data augmentation or
preprocessing, though I really should have. This isn't a major project, so
I didn't do too much work on it.

Absolutely phenomenal job with the simulation! It looks great. The
simulation isn't performing well because there isn't a large amount of data
on high curvature roads. You'll notice in the simulation that the car
drives quite well on low curvature parts of the road (but not straight
sections of course). This can be easily solved by a quick drive around the
residential areas of my city though to get more data.

I might consider working more on this project now that you've made such a
marvelous simulation tool! Let me know if you have any more questions!

-Sully Chen

**Comment by leonardoaraujosantos** [comment]
Cool! Btw if you want to play (Create your own dataset)
I'm trying now to play with the TFRecord and also try to balance the dataset by repeating steering angles that are not 0
Also check it out on drive_on_game.py that I did not need to filter the results:
https://github.com/leonardoaraujosantos/DLMatFramework/blob/master/virtual/tensorDriver/drive_on_game.py#L94

Here is a python notebook showing how unbalance the dataset is right now:
https://github.com/leonardoaraujosantos/DLMatFramework/blob/master/virtual/tensorDriver/ImproveDataset_LMDB.ipynb

Stuff related to the game (Code and builds)
https://github.com/leonardoaraujosantos/DLMatFramework/releases/download/v0.2/WindowsBuild.zip
https://github.com/leonardoaraujosantos/DLMatFramework/releases/download/v0.2/LinuxBuild.zip
Source code of the game
https://github.com/leonardoaraujosantos/DLMatFramework/releases/download/v0.2/UnityProject.zip

**Comment by SullyChen** [comment]
Thanks so much!

-Sully Chen

**Comment by leonardoaraujosantos** [comment]
Sure no problem, I've learn a lot about tensorflow from your code, btw I balanced the dataset, just by repeating the samples that were not to frequent and it improved a lot (I also notice no difference taking out the atan scaling part)
https://github.com/leonardoaraujosantos/DLMatFramework/blob/master/virtual/tensorDriver/ImproveDataset_LMDB.ipynb

Keep taking a look on the code because it seems that using feed_dict to train is also not the best way to use tensorflow anymore.
https://blog.metaflow.fr/tensorflow-how-to-optimise-your-input-pipeline-with-queues-and-multi-threading-e7c3874157e0

Also all the stuff that I'm learning on "Deep learning" I'm adding on this book
https://leonardoaraujosantos.gitbooks.io/artificial-inteligence/content/

**Comment by SullyChen** [comment]
Wow! Looks great.

-Sully Chen
